#spring.application.name=ordering

# ??? SERVER ???
server.port=8080

# ??? DATABASE ???
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PWD}
spring.datasource.username=${DB_USER}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ??? JPA ???
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ??? SWAGGER ???
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ??? APP NAME ???
spring.application.name=retail-ordering


jwt.secret=${YOUR_SECRET_KEY}
jwt.expiration=86400000